import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");

test("web client uses canonical /api/v1 and one synchronized creation workspace", () => {
  const api = fs.readFileSync(path.join(root, "src", "api.ts"), "utf8");
  const http = fs.readFileSync(path.join(root, "src", "http.ts"), "utf8");
  const contracts = fs.readFileSync(path.join(root, "src", "contracts.ts"), "utf8");
  const main = fs.readFileSync(path.join(root, "src", "main.ts"), "utf8");
  const sourceViewer = fs.readFileSync(path.join(root, "src", "source-viewer.ts"), "utf8");
  assert.match(http, /`\/api\/v1\$\{path\}`/);
  assert.match(api, /createInstallPayload\(manifest, executionTarget\)/);
  assert.match(api, /productionAcceptanceTimeoutSeconds\(manifest\)/);
  assert.match(api, /createManifestGenerationPayload\(manifest, draft, executionTarget, idempotencyKey\)/);
  assert.doesNotMatch(api, /createGenerationPayload|generate:\s*\(/);
  assert.match(api, /"\/execution-domains"/);
  assert.match(api, /\/execution-options/);
  assert.match(api, /"\/state"/);
  assert.match(api, /stateEventsUrl/);
  assert.match(api, /jobEventsUrl/);
  assert.match(api, /\/models\?verification_scope=metadata/);
  assert.match(main, /type View = "playground" \| "catalog" \| "overview"/);
  assert.doesNotMatch(main, /type View = .*"viewer"/);
  assert.doesNotMatch(main, /type View = .*"jobs"/);
  const workbench = main.slice(main.indexOf("function playground(): string"), main.indexOf("function catalog(): string"));
  assert.match(workbench, /id="generate"/);
  assert.match(workbench, /id="vrm-canvas"/);
  assert.match(workbench, /id="source-skeleton-canvas"/);
  assert.match(workbench, /重定向前 · 模型骨架/);
  assert.match(workbench, /重定向后 · 最终 VRM/);
  assert.match(workbench, /id="generation-output"/);
  assert.match(main, /function synchronizePersistentState/);
  assert.match(main, /api\.models\(\)/);
  assert.match(main, /api\.jobs\(\)/);
  assert.match(main, /new WebSocket\(stateEventsUrl\(\)\)/);
  assert.match(main, /new WebSocket\(jobEventsUrl\(initial\.id\)\)/);
  assert.match(main, /await nextPaint\(\)/);
  assert.match(main, /virea\.pending-generation\.v1/);
  assert.match(main, /window\.localStorage\.setItem/);
  assert.doesNotMatch(main, /installationStates/);
  assert.doesNotMatch(main, /setTimeout\(resolve, 750\)/);
  assert.match(main, /changedRevisionKeys/);
  assert.match(main, /visibilitychange/);
  assert.match(main, /window\.setInterval\(\(\) => void pollStateRevision\(\)/);
  assert.match(main, /executionDomainSelector\(\)/);
  assert.equal([...main.matchAll(/executionDomainSelector\(/g)].length, 2);
  assert.doesNotMatch(api, /body:\s*JSON\.stringify\(\{\s*model_id/);
  assert.match(api, /\/jobs\/\$\{encodeURIComponent\(jobId\)\}\/result/);
  assert.match(api, /\/source-skeleton/);
  assert.doesNotMatch(api, /`\/jobs\/\$\{jobId\}/);
  assert.match(main, /Motion Studio 0\.4\.0/);
  assert.doesNotMatch(main, /Motion Studio 0\.3/);
  const bootstrap = main.slice(main.indexOf("async function bootstrap"), main.indexOf("void bootstrap"));
  assert.match(bootstrap, /api\.health\(\)/);
  assert.doesNotMatch(bootstrap, /api\.system\(\)/);
  assert.match(bootstrap, /lastRevision = null/);
  assert.match(bootstrap, /stateRevisionKey = ""/);
  assert.match(http, /new AbortController\(\)/);
  assert.match(http, /cache:\s*"no-store"/);
  assert.match(http, /finally\s*\{/);
  assert.match(http, /clearTimeout\(timer\)/);
  assert.match(contracts, /runtime_core_epoch: string \| null/);
  assert.match(contracts, /execution_domain_id\?: string \| null/);
  assert.match(contracts, /execution_target\?:/);
  assert.match(contracts, /virea_integrated: boolean/);
  assert.match(contracts, /inputs: ManifestInputSchema\[\]/);
  assert.match(contracts, /production_acceptance_suite\?: ProductionE2EAcceptanceSuite \| null/);
  assert.match(contracts, /virea\.production_e2e_acceptance_suite\.v1\.0\.0/);
  assert.match(main, /generationInputFields\(manifest, draft\.task\)/);
  assert.match(main, /api\.generateFromFields\(/);
  assert.match(main, /productionAcceptanceForTask\(manifest, draft\.task\)/);
  assert.match(contracts, /verification_scope\?: "metadata" \| "full_integrity"/);
  assert.match(contracts, /integrity_verified\?: boolean/);
  assert.match(main, /capabilityReason/);
  assert.match(contracts, /virea_home: string/);
  assert.match(main, /productionCatalogJobs\(state\.jobs, state\.models\)/);
  assert.match(main, /data-source-empty="true"/);
  assert.match(main, /payload\.virea_home/);
  assert.match(main, /runtime\.runtime_core_epoch/);
  assert.match(contracts, /virea\.source_skeleton_preview\.v1\.0\.0/);
  assert.match(sourceViewer, /model_output_pre_retarget/);
  assert.match(sourceViewer, /vrm_retarget_applied !== false/);
  assert.match(sourceViewer, /new THREE\.LineSegments/);
  assert.doesNotMatch(sourceViewer, /createVRMAnimationClip|VRMAnimationLoaderPlugin|VRMLoaderPlugin/);
});

test("viewer loads VRM and VRMA through the official Pixiv loaders", () => {
  const source = fs.readFileSync(path.join(root, "src", "viewer.ts"), "utf8");
  assert.doesNotMatch(source, /MoMask.*quaternion|SentiAvatar.*pose|HY-Motion.*rotation/i);
  assert.match(source, /VRMLoaderPlugin/);
  assert.match(source, /VRMAnimationLoaderPlugin/);
  assert.match(source, /createVRMAnimationClip/);
  assert.match(source, /ensureVRMLookAtQuaternionProxy\(this\.vrm\)/);
  assert.match(source, /AnimationMixer/);
  assert.match(source, /new THREE\.Timer\(\)/);
  assert.match(source, /this\.timer\.update\(timestamp\)/);
  assert.doesNotMatch(source, /new THREE\.Clock\(\)/);
});

test("production assets stay under the FastAPI /app mount", () => {
  const config = fs.readFileSync(path.join(root, "vite.config.ts"), "utf8");
  assert.match(config, /base:\s*["']\/app\/["']/);
});
