#!/usr/bin/env sh
# Configure one durable VIREA data root for POSIX shells.
set -eu

usage() {
    cat <<'EOF'
Usage: scripts/configure-virea.sh --data-root PATH [--shell-profile PATH]

--data-root PATH       Root of a user-selected data volume. VIREA creates only
                       its home/, environment and dependency-cache directories
                       below this directory.
--shell-profile PATH   Shell startup file to source the generated environment.
                       If omitted, bash uses ~/.bashrc, zsh uses ~/.zshrc, and
                       other POSIX shells use ~/.profile.
EOF
}

data_root=''
shell_profile=''
while [ "$#" -gt 0 ]; do
    case "$1" in
        --data-root)
            [ "$#" -ge 2 ] || { usage >&2; exit 2; }
            data_root=$2
            shift 2
            ;;
        --shell-profile)
            [ "$#" -ge 2 ] || { usage >&2; exit 2; }
            shell_profile=$2
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
done

[ -n "$data_root" ] || { usage >&2; exit 2; }

repository_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
mkdir -p -- "$data_root"
resolved_data_root=$(CDPATH= cd -- "$data_root" && pwd -P)
case "$resolved_data_root" in
    "$repository_root"|"$repository_root"/*)
        printf '%s\n' "data root must be outside the cloned repository: $repository_root" >&2
        exit 2
        ;;
esac

case ${SHELL:-} in
    */bash) default_profile="$HOME/.bashrc" ;;
    */zsh) default_profile="$HOME/.zshrc" ;;
    *) default_profile="$HOME/.profile" ;;
esac
[ -n "$shell_profile" ] || shell_profile=$default_profile

config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}/virea
environment_file="$config_home/environment.sh"
mkdir -p -- "$config_home" "$resolved_data_root/home" \
    "$resolved_data_root/dev-venv" "$resolved_data_root/uv-cache" \
    "$resolved_data_root/home/cache/huggingface" "$resolved_data_root/npm-cache" \
    "$resolved_data_root/pnpm-store"

shell_quote() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

temporary_environment="$environment_file.tmp-$$"
umask 077
{
    printf '%s\n' '# Generated by VIREA; rerun configure-virea.sh to change the data root.'
    printf 'export VIREA_HOME=%s\n' "$(shell_quote "$resolved_data_root/home")"
    printf 'export UV_PROJECT_ENVIRONMENT=%s\n' "$(shell_quote "$resolved_data_root/dev-venv")"
    printf 'export UV_CACHE_DIR=%s\n' "$(shell_quote "$resolved_data_root/uv-cache")"
    printf 'export HF_HOME=%s\n' "$(shell_quote "$resolved_data_root/home/cache/huggingface")"
    printf 'export NPM_CONFIG_CACHE=%s\n' "$(shell_quote "$resolved_data_root/npm-cache")"
    printf 'export NPM_CONFIG_STORE_DIR=%s\n' "$(shell_quote "$resolved_data_root/pnpm-store")"
} > "$temporary_environment"
mv -f -- "$temporary_environment" "$environment_file"

mkdir -p -- "$(dirname -- "$shell_profile")"
touch -- "$shell_profile"
if ! grep -Fq '# >>> VIREA managed environment >>>' "$shell_profile"; then
    cat >> "$shell_profile" <<'EOF'

# >>> VIREA managed environment >>>
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/virea/environment.sh" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/virea/environment.sh"
# <<< VIREA managed environment <<<
EOF
fi

printf '%s\n' "VIREA data root configured: $resolved_data_root"
printf '%s\n' "Shell hook installed in: $shell_profile"
printf '%s\n' "Run '. $environment_file' now, or open a new terminal."
